apiVersion: apps/v1
kind: Deployment
metadata:
  name: nerdd-backend
  labels:
    app: nerdd-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nerdd-backend
  template:
    metadata:
      labels:
        app: nerdd-backend
    spec:
      containers:
        - name: nerdd-backend
          image: ghcr.io/molinfo-vienna/nerdd-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          args:
            - --config-name
            - production
            - ++db.host=$(DB_HOST)
            - ++db.port=$(DB_PORT)
            - ++channel.name=$(CHANNEL)
            - ++channel.broker_url=$(BROKER_URL)
            - ++channel.broker_username=$(BROKER_USERNAME)
            - ++channel.broker_password=$(BROKER_PASSWORD)
            - ++media_root=/data
            - ++s3_url=$(S3_URL)
            - ++s3_bucket=$(S3_BUCKET)
            - ++s3_access_key_id=$(S3_ACCESS_KEY_ID)
            - ++s3_secret_access_key=$(S3_SECRET_ACCESS_KEY)
          env:
            - name: DB_HOST
              value: rethinkdb
            - name: DB_PORT
              value: "28015"
            - name: CHANNEL
              valueFrom:
                secretKeyRef:
                  name: broker-config-backend
                  key: channel
            - name: BROKER_URL
              valueFrom:
                secretKeyRef:
                  name: broker-config-backend
                  key: broker_url
            - name: BROKER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: broker-config-backend
                  key: broker_username
            - name: BROKER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: broker-config-backend
                  key: broker_password
            - name: S3_URL
              valueFrom:
                secretKeyRef:
                  name: s3-config-backend
                  key: s3_url
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: s3-config-backend
                  key: s3_bucket
            - name: S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-config-backend
                  key: s3_access_key_id
            - name: S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-config-backend
                  key: s3_secret_access_key
            # let users see a maintenance page and disable api:
            # - name: MAINTENANCE_MODE
            #   value: "true"
          resources:
            requests:
              cpu: 500m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
      affinity:
        # distribute instances across nodes
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - nerdd-backend
              topologyKey: "kubernetes.io/hostname"
