apiVersion: apps/v1
kind: Deployment
metadata:
  name: nerdd-backend
spec:
  template:
    spec:
      containers:
        - name: nerdd-backend
          env:
            - name: DB_HOST
              value: rethinkdb.dev
            # let users see a maintenance page and disable api:
            # - name: MAINTENANCE_MODE
            #   value: "true"
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-media
